In [46]:
import pandas as pd 
import datetime
from neo import io

In [47]:
ttl_log_file = '/Users/johnmarshall/Dropbox (Personal)/Operant_data/MGluR5_D1_cre_run002/162_2019_7_5 11h40m Task29_TtlLog.txt'
abf_file = '/users/johnmarshall/Documents/Analysis/PhotometryData/Old/September2018/AAV_syn29_002/18919000_F_F0.h5'

In [48]:
r = io.AxonIO(filename='/users/johnmarshall/Documents/Analysis/PhotometryData/Old/September2018/AAV_syn29_002/18919000.abf')

In [50]:
r.times

AttributeError: 'AxonIO' object has no attribute 'times'

In [54]:
abf_file_df = pd.read_hdf(abf_file)

In [14]:
ttl = pd.read_table(ttl_log_file, sep=',')

In [18]:
ttl

         Unnamed: 0  TTL ON Unnamed: 2 Unnamed: 3 TTL OFF
No   hr         min     sec         hr        min     sec
1    11           3   8.471        NaN        NaN     NaN
     NaN        NaN     NaN         11          3   9.432
2    11           3  10.440        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  10.539
3    11           3  12.445        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  12.544
4    11           3  14.457        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  14.558
5    11           3  16.425        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  16.526
6    11           3  18.442        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  18.540
7    11           3  20.440        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  20.541
8    11           3  22.426        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  22.527
9    11           3  24.443        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  24.541
10   11           3  26.440        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  26.543
11   11           3  28.456        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  28.553
12   11           3  30.426        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  30.526
13   11           3  32.441        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  32.540
14   11           3  34.451        NaN        NaN     NaN
     NaN        NaN     NaN         11          3  34.554
15   11           3  36.447        NaN        NaN     NaN
...             ...     ...        ...        ...     ...
1112 11          40  10.452        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  10.556
1113 11          40  12.439        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  12.541
1114 11          40  14.424        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  14.525
1115 11          40  16.438        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  16.530
1116 11          40  18.453        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  18.554
1117 11          40  20.442        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  20.543
1118 11          40  22.453        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  22.523
1119 11          40  24.449        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  24.549
1120 11          40  26.456        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  26.557
1121 11          40  28.424        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  28.530
1122 11          40  30.453        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  30.553
1123 11          40  32.462        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  32.541
1124 11          40  34.462        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  34.526
1125 11          40  36.424        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  36.531
1126 11          40  38.426        NaN        NaN     NaN
     NaN        NaN     NaN         11         40  38.527

[2253 rows x 5 columns]

In [19]:
ttl_0_seconds = (11*3600)+(3*60)+8.471

In [24]:
ttl_1_seconds = (11*3600)+(3*60)+10.440

In [25]:
ttl_1_seconds

39790.44

In [23]:
ttl_0_seconds

39788.471

In [26]:
diff = ttl_1_seconds-ttl_0_seconds

In [27]:
diff

1.9690000000045984

In [22]:
str(datetime.timedelta(ttl_0_seconds))

'39788 days, 11:18:14.400000'

In [12]:
abf_file = pd.read_hdf(abf_file)

In [60]:
start_times = [8, 10, 12, 13, 14, 15]

In [61]:
abf_file_df

                 channel_1_demod  channel_1_demod_F_F0  channel_2_demod  \
sweep
sweep001 0              0.030727              0.958625         0.351495
         1              0.030723              0.958625         0.351483
         2              0.030719              0.958625         0.351471
         3              0.030715              0.958625         0.351459
         4              0.030711              0.958625         0.351447
         5              0.030707              0.958625         0.351434
         6              0.030703              0.958625         0.351421
         7              0.030700              0.958625         0.351408
         8              0.030696              0.958625         0.351394
         9              0.030693              0.958625         0.351381
         10             0.030690              0.958625         0.351367
         11             0.030687              0.958625         0.351353
         12             0.030684              0.958625         0.351339
         13             0.030681              0.958625         0.351325
         14             0.030679              0.958625         0.351311
         15             0.030676              0.958625         0.351297
         16             0.030674              0.958625         0.351283
         17             0.030672              0.958625         0.351269
         18             0.030670              0.958625         0.351254
         19             0.030669              0.958625         0.351240
         20             0.030667              0.958625         0.351225
         21             0.030666              0.958625         0.351211
         22             0.030665              0.958625         0.351197
         23             0.030664              0.958625         0.351182
         24             0.030663              0.958625         0.351168
         25             0.030662              0.958625         0.351153
         26             0.030662              0.958625         0.351139
         27             0.030662              0.958625         0.351125
         28             0.030662              0.958625         0.351110
         29             0.030662              0.958625         0.351096
...                          ...                   ...              ...
sweep006 729974         0.023906              1.020466         0.340680
         729975         0.023902              1.020290         0.340689
         729976         0.023898              1.020106         0.340699
         729977         0.023894              1.019914         0.340708
         729978         0.023889              1.019714         0.340717
         729979         0.023884              1.019507         0.340726
         729980         0.023879              1.019293         0.340734
         729981         0.023874              1.019072         0.340743
         729982         0.023869              1.018843         0.340751
         729983         0.023864              1.018608         0.340759
         729984         0.023858              1.018367         0.340767
         729985         0.023852              1.018119         0.340774
         729986         0.023846              1.017865         0.340782
         729987         0.023840              1.017606         0.340789
         729988         0.023834              1.017341         0.340795
         729989         0.023828              1.017071         0.340802
         729990         0.023822              1.016795         0.340808
         729991         0.023815              1.016515         0.340814
         729992         0.023809              1.016231         0.340820
         729993         0.023802              1.015942         0.340826
         729994         0.023795              1.015650         0.340831
         729995         0.023788              1.015354         0.340836
         729996         0.023781              1.015055         0.340840
         729997         0.023774              1.014752         0.340845
         729998         0.023767              1.014447         0.340849
         729999         0.023760              1.014139         0.340853
         730000         0.023753              1.013829         0.340857
         730001         0.023746              1.013517         0.340860
         730002         0.023739              1.013203         0.340863
         730003         0.023731              1.012887         0.340867

                 channel_2_demod_F_F0  encoder_windowed  \
sweep
sweep001 0                   0.999801          0.042419
         1                   0.999801          0.042725
         2                   0.999801          0.041809
         3                   0.999801          0.042114
         4                   0.999801          0.046692
         5                   0.999801          0.045776
         6                   0.999801          0.044861
         7                   0.999801          0.044250
         8                   0.999801          0.044556
         9                   0.999801          0.046692
         10                  0.999801          0.045471
         11                  0.999801          0.044861
         12                  0.999801          0.046387
         13                  0.999801          0.046692
         14                  0.999801          0.046692
         15                  0.999801          0.046082
         16                  0.999801          0.046082
         17                  0.999801          0.044556
         18                  0.999801          0.046082
         19                  0.999801          0.046387
         20                  0.999801          0.044250
         21                  0.999801          0.044556
         22                  0.999801          0.044250
         23                  0.999801          0.044861
         24                  0.999801          0.044556
         25                  0.999801          0.043640
         26                  0.999801          0.042725
         27                  0.999801          0.042419
         28                  0.999801          0.042725
         29                  0.999801          0.044861
...                               ...               ...
sweep006 729974              0.996848          0.045471
         729975              0.996876          0.044556
         729976              0.996903          0.046692
         729977              0.996930          0.046082
         729978              0.996957          0.045471
         729979              0.996983          0.047607
         729980              0.997008          0.043945
         729981              0.997033          0.046692
         729982              0.997057          0.044861
         729983              0.997081          0.044861
         729984              0.997104          0.042419
         729985              0.997126          0.042725
         729986              0.997148          0.044250
         729987              0.997168          0.046692
         729988              0.997189          0.045776
         729989              0.997208          0.046387
         729990              0.997227          0.045776
         729991              0.997244          0.046692
         729992              0.997261          0.046387
         729993              0.997278          0.046387
         729994              0.997293          0.046387
         729995              0.997308          0.046082
         729996              0.997322          0.046692
         729997              0.997335          0.047607
         729998              0.997348          0.046082
         729999              0.997360          0.046082
         730000              0.997371          0.045471
         730001              0.997381          0.047913
         730002              0.997391          0.043640
         730003              0.997400          0.043640

                 fluorescence_channel_1_windowed     time
sweep
sweep001 0                              3.944397  14.9998
         1                              3.597107  14.9999
         2                              2.861023  15.0000
         3                              1.961060  15.0001
         4                              1.164551  15.0002
         5                              0.518799  15.0003
         6                              0.020447  15.0004
         7                             -0.296021  15.0005
         8                             -0.442200  15.0006
         9                             -0.500488  15.0007
         10                            -0.426941  15.0008
         11                            -0.262756  15.0009
         12                            -0.063782  15.0010
         13                             0.421448  15.0011
         14                             1.178589  15.0012
         15                             2.052917  15.0013
         16                             2.912292  15.0014
         17                             3.575439  15.0015
         18                             3.959656  15.0016
         19                             4.042664  15.0017
         20                             3.867798  15.0018
         21                             3.445129  15.0019
         22                             2.874451  15.0020
         23                             2.253723  15.0021
         24                             1.543274  15.0022
         25                             0.838318  15.0023
         26                             0.279236  15.0024
         27                            -0.125732  15.0025
         28                            -0.354004  15.0026
         29                            -0.415344  15.0027
...                                          ...      ...
sweep006 729974                         0.422363  87.9972
         729975                         1.187439  87.9973
         729976                         2.086487  87.9974
         729977                         3.040771  87.9975
         729978                         3.899536  87.9976
         729979                         4.480286  87.9977
         729980                         4.668579  87.9978
         729981                         4.300842  87.9979
         729982                         3.425293  87.9980
         729983                         2.355652  87.9981
         729984                         1.417542  87.9982
         729985                         0.635681  87.9983
         729986                         0.045471  87.9984
         729987                        -0.341187  87.9985
         729988                        -0.536194  87.9986
         729989                        -0.604248  87.9987
         729990                        -0.543518  87.9988
         729991                        -0.358276  87.9989
         729992                        -0.143738  87.9990
         729993                         0.311890  87.9991
         729994                         1.085815  87.9992
         729995                         1.964417  87.9993
         729996                         2.808533  87.9994
         729997                         3.446045  87.9995
         729998                         3.801880  87.9996
         729999                         3.853455  87.9997
         730000                         3.515625  87.9998
         730001                         2.813416  87.9999
         730002                         1.939087  88.0000
         730003                         1.165161  88.0001

[4380024 rows x 7 columns]

In [66]:
sweeps = sorted(list(set(abf_file_df.index.get_level_values(level=0))))

In [67]:
sweeps

['sweep001', 'sweep002', 'sweep003', 'sweep004', 'sweep005', 'sweep006']

In [72]:
dfs = []
for sweepname, sweep in zip(sweeps, range(len(sweeps))):
    dfs.append(pd.DataFrame(abf_file_df['time']+start_times[sweep]))

In [76]:
dfs_df = pd.concat(dfs)

In [81]:
dfs_df = dfs_df.rename(index=str, columns={'time': 'abs_time'})

In [82]:
dfs_df

                 abs_time
sweep
sweep001 0        22.9998
         1        22.9999
         2        23.0000
         3        23.0001
         4        23.0002
         5        23.0003
         6        23.0004
         7        23.0005
         8        23.0006
         9        23.0007
         10       23.0008
         11       23.0009
         12       23.0010
         13       23.0011
         14       23.0012
         15       23.0013
         16       23.0014
         17       23.0015
         18       23.0016
         19       23.0017
         20       23.0018
         21       23.0019
         22       23.0020
         23       23.0021
         24       23.0022
         25       23.0023
         26       23.0024
         27       23.0025
         28       23.0026
         29       23.0027
...                   ...
sweep006 729974  102.9972
         729975  102.9973
         729976  102.9974
         729977  102.9975
         729978  102.9976
         729979  102.9977
         729980  102.9978
         729981  102.9979
         729982  102.9980
         729983  102.9981
         729984  102.9982
         729985  102.9983
         729986  102.9984
         729987  102.9985
         729988  102.9986
         729989  102.9987
         729990  102.9988
         729991  102.9989
         729992  102.9990
         729993  102.9991
         729994  102.9992
         729995  102.9993
         729996  102.9994
         729997  102.9995
         729998  102.9996
         729999  102.9997
         730000  102.9998
         730001  102.9999
         730002  103.0000
         730003  103.0001

[26280144 rows x 1 columns]

In [83]:
pd.concat([abf_file_df, dfs_df ], axis=1)

Exception: cannot handle a non-unique multi-index!

In [38]:
touch_time_1 = (11*3600)+(3*60)+44.442

In [42]:
rel_time = touch_time_1-ttl_0_seconds

In [43]:
df_sort = abf_file.ix[(abf_file['time']-rel_time).abs().argsort()[:2]]

/Users/johnmarshall/miniconda3/envs/miniscoPy/lib/python3.6/site-packages/ipykernel/__main__.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':

In [94]:
list(df_sort.index.get_level_values(level=0))

['sweep002', 'sweep004']

In [95]:
list(df_sort.index.get_level_values(level=1))

[209712, 209712]